### ISSUE TITLE
Coupon is not removed after checkout and shows up in next session also

### ISSUE THREAD

**Issue by shivampatel22** [PacktPublishing/Django-4-by-example#15]
'coupon_id' should be removed from session after checkout is complete.

 **Steps to replicate**
- Add items in cart.
- Apply any active coupon.
- Place order.
- New session is started.
- Add items in cart. *previously applied coupon is already applied on cart detail page*

**Comment by PRCervera** [comment]
You have to add ...

request.session['coupon_id'] = None

after ...

 cart.clear()

in cart's views.py

**Comment by zenx** [comment]
Thank you @PRCervera.

@shivampatel22 as @PRCervera mentions, you can remove `coupon_id` from the session in `orders/views.py` after clearing the cart in this line: https://github.com/PacktPublishing/Django-4-by-example/blob/f4d6a3df49fb851b96466bf6327dc93cc24f8f58/Chapter11/myshop/orders/views.py#L30

**Comment by shivampatel22** [comment]
Thanks @PRCervera and @zenx.

**Comment by Shush1k** [comment]
I spent a little time thinking why the coupon stays in the session, then I thought I had missed this point in the book. Nice issue
