### ISSUE TITLE
Please support

### ISSUE THREAD

**Issue by bantu94** [PacktPublishing/Django-4-by-example#17]
the whole base.html is giving me errors, ANY UPDATES? when i runserver to accounts/login , it gets stack there even when i go to accounts/logout the page still remains in the  login. the errors are only in base.html starting from the {% load static %}

**Comment by zenx** [comment]
@bantu94 can you paste the error you are getting?

**Comment by bantu94** [comment]
Ooooooopps I instead went to do a blog project, I actually had to close this issue. Thanks will let you if encounter another problem.
