### ISSUE TITLE
chapter 1: typo in figure 1.4 page 14

### ISSUE THREAD

**Issue by abe-101** [PacktPublishing/Django-4-by-example#23]
In figure 1.4 there seems to be a mistake with  `body` being a foreign key 

![image](https://user-images.githubusercontent.com/82916197/203058435-626bb2a3-664e-4c3e-9758-cf65ef77ec1c.png)

 Is it supposed to be a a textField
 just like it is in figure 1.5:
 
![image](https://user-images.githubusercontent.com/82916197/203058656-a54d9925-0d3e-415b-b41c-b49b86f87c30.png)

**Comment by zenx** [comment]
@abe-101 thank you for reporting this typo. You are right, in _Figure 1.4_ the `body` field should be a `TextField`.

**Comment by zenx** [comment]
Added to Errata in b14c4bcd9a53b9ec2a481f3fecc8bb31c575ce12
