### ISSUE TITLE
Shop e-mail invoices

### ISSUE THREAD

**Issue by PRCervera** [PacktPublishing/Django-4-by-example#24]
Hi,

I cannot print the translated invoice that is sent by email in the payment process.

It always comes out with the source language. 

Template process.html is fully adapted.

Does anyone else have this problem?

Maybe Celery needs some parameters about the language active... I don't know.

I would appreciate some help,

Thank you.

**Comment by PRCervera** [comment]
Sorry,

Template name is pdf.html.

Regards

**Comment by zenx** [comment]
@PRCervera can you attach your `views.py` and `pdf.html` files?

**Comment by PRCervera** [comment]
Thank you !

[orders.zip](https://github.com/PacktPublishing/Django-4-by-example/files/10067185/orders.zip)
[payments.zip](https://github.com/PacktPublishing/Django-4-by-example/files/10067200/payments.zip)

**Comment by zenx** [comment]
Sorry @PRCervera, I didn't understand your issue correctly previously.

Celery workers are not aware of the current language. Django determines the current language using the `LocaleMiddleware`. As celery tasks are processed out of any request scope, they fall back to the base language defined with the `LANGUAGE_CODE` setting. You can do the following to use the request language for the email sent with Celery:

In the `order_create` view in `order/views.py` add `request.LANGUAGE_CODE` as follows:
```
order_created.delay(order.id, request.LANGUAGE_CODE)
```

And then in `order/tasks.py` you can activate the given language before sending the email:
```
from django.utils.translation import activate
# ...

@shared_task
def order_created(order_id, language_code):
    activate(language_code)
    # ...
```

This is a good improvement to add to the book examples. Thank you.

**Comment by PRCervera** [comment]
Now it works !

Thanks to you !!!
