### ISSUE TITLE
Book code is wrong on chapter 16 pertaining to the ASGI_APPLICATION

### ISSUE THREAD

**Issue by paula-em-lafon** [PacktPublishing/Django-4-by-example#38]
I'm goint through the book through the O'Reilly site.

It comes with the follwoing line to add to settings.py

`ASGI_APPLICATION = 'educa.routing.application'`

But the code on this repository has got:

`ASGI_APPLICATION = 'educa.asgi.application'`

which works.

**Comment by zenx** [comment]
Thank you! This was added to the Errata in https://github.com/PacktPublishing/Django-4-by-example/blob/main/README.md #
